### ISSUE TITLE
Delete request not working using geoserver 2.16.2

### ISSUE THREAD

**Issue by ZakUrl** [SKalt/geojson-to-wfs-t-2#30]
The request built by the Delete function doesn't work for geoserver 2.16.2 and using WFS 2.

bad request:

![deleteRequestIssue](https://user-images.githubusercontent.com/15875593/75241344-34406d00-57c6-11ea-9e8b-2fdd090efc05.png)

To make it work, I had to remove the namespace and the string "Type" wich was added in the return of the typeName function.

Here is an example of a working request :

![workingDeleteRequest](https://user-images.githubusercontent.com/15875593/75244754-a9af3c00-57cc-11ea-9388-16a3e72acb39.png)

**Comment by SKalt** [comment]
Hi, could you provide the correct and incorrect requests as text?

**Comment by ZakUrl** [comment]
yes here they are :

good :
-------

<wfs:Transaction xmlns:c4i="http://localhost:8080/geoserver/wfs/DescribeFeatureType?typename=c4i" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xsi:schemaLocation="http://www.opengis.net/wfs/2.0
http://schemas.opengis.net/wfs/2.0/wfs.xsd" service="WFS" version="2.0.0">
    <wfs:Delete typeName="agent_way_points">
        <fes:Filter>
            <fes:ResourceId rid="agent_way_points.12"/>
        </fes:Filter>
    </wfs:Delete>
</wfs:Transaction>


bad:
------

<wfs:Transaction xmlns:c4i="http://localhost:8080/geoserver/wfs/DescribeFeatureType?typename=c4i" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:wfs="http://www.opengis.net/wfs/2.0" xsi:schemaLocation="http://www.opengis.net/wfs/2.0
http://schemas.opengis.net/wfs/2.0/wfs.xsd" service="WFS" version="2.0.0">
    <wfs:Delete typeName="c4i:agent_way_pointsType">
        <fes:Filter>
            <fes:ResourceId rid="agent_way_points.12"/>
        </fes:Filter>
    </wfs:Delete>
</wfs:Transaction>

**Comment by ZakUrl** [comment]
The problem is located in the 'ensure.js' file at line 39:
/**
 * return a correctly-formatted typeName
 * @function
 * @param {String} ns namespace
 * @param {String} layer layer name
 * @param {String} typeName typeName to check
 * @return {String} a correctly-formatted typeName
 * @throws {Error} if typeName it cannot form a typeName from ns and layer
 */
export const typeName = (ns, layer, typeName) =>{
  if (!typeName && !(ns && layer)) {
    throw new Error(`no typename possible: ${
      JSON.stringify({typeName, ns, layer}, null, 2)
    }`);
  }
  return typeName || `${ns}:${layer}Type`;
};

the modification I did on local is the following:
"""
  return typeName || `${layer}`;
"""
so I removed the namespace and the string "Type" next to the layer

**Comment by SKalt** [comment]
Sounds good. PR in that change and I'll accept it and republish a patch version of the module.  I'm about to start work, so I'll likely have ~1h latency.

Notes for further verifcation of this change: https://gist.github.com/SKalt/0f4b757209687331c8a1d40aecbf69f9 <- has links to `delete` the WFS-T 2 spec 

<details><summary>personal aside</summary>

Apologies for re-editing your issue comments. Syntax highlighting and code formatting are nitpicks I often make.  Since I was one who cared about the trivial changes, it was on me to make them. 

In case you're interested in acquiring my prejudices about how `<code>` should look in PRs, issues, and most major blogging platforms, I'd recommend reading through  https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet#code-and-syntax-highlighting. 
</details>

**Comment by SKalt** [comment]
Fixed in #31, published in https://www.npmjs.com/package/geojson-to-wfs-t-2/v/1.5.2
